 
ME_Processing_Resource Me_Regular_Processor cpu1 Proc_Res_Canvas 200 210 
ME_Processing_Resource Me_Regular_Processor cpu2 Proc_Res_Canvas 520 125 
ME_Processing_Resource Me_Packet_Based_Network can Proc_Res_Canvas 610 233 
ME_Timer Me_System_Timer cpu1 Proc_Res_Canvas 40 210 
ME_Timer Me_System_Timer cpu2 Proc_Res_Canvas 360 125 
ME_Driver Me_Packet_Driver cpu2,can Proc_Res_Canvas 40 125 
ME_Driver Me_Packet_Driver cpu1,can Proc_Res_Canvas 452 272 
ME_Scheduler Me_Primary_Scheduler cpu1_sched Proc_Res_Canvas 360 40 
ME_Scheduler Me_Primary_Scheduler cpu2 Proc_Res_Canvas 200 40 
ME_Scheduler Me_Primary_Scheduler can Proc_Res_Canvas 40 40 
ME_Scheduler Me_Primary_Scheduler cpu1_sched Sched_Server_Canvas 520 210 
ME_Scheduler Me_Primary_Scheduler cpu2 Sched_Server_Canvas 520 125 
ME_Scheduler Me_Primary_Scheduler can Sched_Server_Canvas 200 40 
ME_Scheduling_Server Me_Server read Sched_Server_Canvas 40 295 
ME_Scheduling_Server Me_Server display Sched_Server_Canvas 360 210 
ME_Scheduling_Server Me_Server check Sched_Server_Canvas 200 210 
ME_Scheduling_Server Me_Server sensor_isr Sched_Server_Canvas 40 210 
ME_Scheduling_Server Me_Server kbd_isr Sched_Server_Canvas 360 125 
ME_Scheduling_Server Me_Server can_isr Sched_Server_Canvas 200 125 
ME_Scheduling_Server Me_Server can_send Sched_Server_Canvas 40 125 
ME_Scheduling_Server Me_Server can_isr2 Sched_Server_Canvas 520 40 
ME_Scheduling_Server Me_Server msg_srv Sched_Server_Canvas 360 40 
ME_Scheduling_Server Me_Server read_remote Sched_Server_Canvas 40 40 
ME_Shared_Resource Me_Immediate_Ceiling_Resource screen Shared_Res_Canvas 200 40 
ME_Shared_Resource Me_Immediate_Ceiling_Resource measmnt_buffer Shared_Res_Canvas 40 40 
ME_Operation Me_Simple_Operation wite_avg Operation_Canvas 200 295 
ME_Operation Me_Simple_Operation write_record Operation_Canvas 40 295 
ME_Operation Me_Simple_Operation put_temp Operation_Canvas 520 210 
ME_Operation Me_Simple_Operation get_avg_temp Operation_Canvas 360 210 
ME_Operation Me_Simple_Operation get_record Operation_Canvas 200 210 
ME_Operation Me_Enclosing_Operation display Operation_Canvas 40 210 
ME_Operation Me_Enclosing_Operation read Operation_Canvas 520 125 
ME_Operation Me_Enclosing_Operation check Operation_Canvas 360 125 
ME_Operation Me_Simple_Operation sensor_isr Operation_Canvas 200 125 
ME_Operation Me_Simple_Operation kbd_isr Operation_Canvas 40 125 
ME_Operation Me_Simple_Operation can_send Operation_Canvas 520 40 
ME_Operation Me_Simple_Operation can_rec Operation_Canvas 360 40 
ME_Operation Me_Simple_Operation read_remote Operation_Canvas 200 40 
ME_Operation Me_Message_Transmission_Operation msg Operation_Canvas 40 40 
ME_Transaction Me_Regular_Transaction tr_read Transaction_Canvas 360 40 
ME_Transaction Me_Regular_Transaction tr_display Transaction_Canvas 200 40 
ME_Transaction Me_Regular_Transaction tr_check Transaction_Canvas 40 40 
ME_Link Me_External_Link sensor,tr_read tr_read 85 55 
ME_Link Me_Internal_Link put,tr_read tr_read 1605 55 
ME_Link Me_Internal_Link i1,tr_read tr_read 1225 55 
ME_Link Me_Internal_Link i11,tr_read tr_read 465 55 
ME_Link Me_Internal_Link i12,tr_read tr_read 845 55 
ME_Link Me_External_Link dis,tr_display tr_display 85 55 
ME_Link Me_Internal_Link disp_out,tr_display tr_display 465 55 
ME_Link Me_External_Link rec,tr_check tr_check 85 55 
ME_Link Me_Internal_Link rec_out,tr_check tr_check 845 55 
ME_Link Me_Internal_Link i2,tr_check tr_check 465 55 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_read tr_read 1370 40 
ME_Event_Handler Me_Simple_Event_Handler 2,tr_read tr_read 230 40 
ME_Event_Handler Me_Simple_Event_Handler 3,tr_read tr_read 990 40 
ME_Event_Handler Me_Simple_Event_Handler 4,tr_read tr_read 610 40 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_display tr_display 230 40 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_check tr_check 610 40 
ME_Event_Handler Me_Simple_Event_Handler 2,tr_check tr_check 230 40 
