 
ME_Processing_Resource Me_Regular_Processor cpu1 Proc_Res_Canvas 15 15 
ME_Scheduler Me_Primary_Scheduler sc_cpu1 Proc_Res_Canvas 217 29 
ME_Scheduler Me_Primary_Scheduler sc_cpu1 Sched_Server_Canvas 252 14 
ME_Scheduling_Server Me_Server ss_bursty Sched_Server_Canvas 15 15 
ME_Scheduling_Server Me_Server ss_low Sched_Server_Canvas 482 32 
ME_Scheduling_Server Me_Server ss_bursty_2 Sched_Server_Canvas 71 168 
ME_Scheduling_Server Me_Server ss_bursty_3 Sched_Server_Canvas 225 233 
ME_Scheduling_Server Me_Server ss_bursty_4 Sched_Server_Canvas 419 218 
ME_Operation Me_Simple_Operation low Operation_Canvas 15 15 
ME_Operation Me_Simple_Operation bursty Operation_Canvas 204 12 
ME_Transaction Me_Regular_Transaction low Transaction_Canvas 15 15 
ME_Transaction Me_Regular_Transaction bursty Transaction_Canvas 222 14 
ME_Link Me_External_Link e1,low low 15 15 
ME_Link Me_Internal_Link e2,low low 135 15 
ME_Link Me_External_Link e1,bursty bursty 165 15 
ME_Link Me_Internal_Link e2,bursty bursty 294 161 
ME_Link Me_Internal_Link e3,bursty bursty 544 167 
ME_Link Me_Internal_Link e4,bursty bursty 789 162 
ME_Link Me_Internal_Link e5,bursty bursty 954 13 
ME_Link Me_Internal_Link e21,bursty bursty 408 161 
ME_Link Me_Internal_Link e31,bursty bursty 662 163 
ME_Link Me_Internal_Link e41,bursty bursty 915 162 
ME_Event_Handler Me_Simple_Event_Handler 1,low low 129 97 
ME_Event_Handler Me_Simple_Event_Handler 1,bursty bursty 480 90 
ME_Event_Handler Me_Simple_Event_Handler 2,bursty bursty 668 89 
ME_Event_Handler Me_Simple_Event_Handler 3,bursty bursty 919 89 
ME_Event_Handler Me_Simple_Event_Handler 4,bursty bursty 294 202 
ME_Event_Handler Me_Simple_Event_Handler 5,bursty bursty 524 201 
ME_Event_Handler Me_Simple_Event_Handler 6,bursty bursty 796 204 
ME_Event_Handler Me_Simple_Event_Handler 7,bursty bursty 280 87 
