 
ME_Processing_Resource Me_Regular_Processor cpu_1 Proc_Res_Canvas 200 40 
ME_Scheduler Me_Primary_Scheduler cpu_1 Proc_Res_Canvas 40 40 
ME_Scheduler Me_Primary_Scheduler cpu_1 Sched_Server_Canvas 520 40 
ME_Scheduling_Server Me_Server control_task Sched_Server_Canvas 40 125 
ME_Scheduling_Server Me_Server planning_task Sched_Server_Canvas 360 40 
ME_Scheduling_Server Me_Server status_task Sched_Server_Canvas 200 40 
ME_Scheduling_Server Me_Server emergency Sched_Server_Canvas 40 40 
ME_Shared_Resource Me_Immediate_Ceiling_Resource data_server Shared_Res_Canvas 200 40 
ME_Shared_Resource Me_Immediate_Ceiling_Resource comm_server Shared_Res_Canvas 40 40 
ME_Operation Me_Simple_Operation read Operation_Canvas 520 125 
ME_Operation Me_Simple_Operation write Operation_Canvas 360 125 
ME_Operation Me_Simple_Operation send Operation_Canvas 200 125 
ME_Operation Me_Simple_Operation receive Operation_Canvas 40 125 
ME_Operation Me_Enclosing_Operation control Operation_Canvas 403 23 
ME_Operation Me_Enclosing_Operation planning Operation_Canvas 484 236 
ME_Operation Me_Enclosing_Operation status Operation_Canvas 213 221 
ME_Operation Me_Simple_Operation emergency Operation_Canvas 40 40 
ME_Transaction Me_Regular_Transaction control_task Transaction_Canvas 520 40 
ME_Transaction Me_Regular_Transaction planning_task Transaction_Canvas 360 40 
ME_Transaction Me_Regular_Transaction status_task Transaction_Canvas 200 40 
ME_Transaction Me_Regular_Transaction emergency Transaction_Canvas 40 40 
ME_Link Me_External_Link e1,control_task control_task 85 55 
ME_Link Me_Internal_Link o1,control_task control_task 465 55 
ME_Link Me_External_Link e2,planning_task planning_task 85 55 
ME_Link Me_Internal_Link o2,planning_task planning_task 465 55 
ME_Link Me_External_Link e3,status_task status_task 85 55 
ME_Link Me_Internal_Link o3,status_task status_task 465 55 
ME_Link Me_External_Link e4,emergency emergency 85 55 
ME_Link Me_Internal_Link o4,emergency emergency 465 55 
ME_Event_Handler Me_Simple_Event_Handler 1,control_task control_task 230 40 
ME_Event_Handler Me_Simple_Event_Handler 1,planning_task planning_task 230 40 
ME_Event_Handler Me_Simple_Event_Handler 1,status_task status_task 230 40 
ME_Event_Handler Me_Simple_Event_Handler 1,emergency emergency 230 40 
