 
ME_Processing_Resource Me_Regular_Processor enginemanagement Proc_Res_Canvas 465 235 
ME_Processing_Resource Me_Regular_Processor bodycontroller Proc_Res_Canvas 29 239 
ME_Processing_Resource Me_Regular_Processor canbus Proc_Res_Canvas 520 40 
ME_Scheduler Me_Primary_Scheduler enginemanagement Proc_Res_Canvas 307 143 
ME_Scheduler Me_Primary_Scheduler bodycontroller Proc_Res_Canvas 127 136 
ME_Scheduler Me_Primary_Scheduler canbus Proc_Res_Canvas 285 40 
ME_Scheduler Me_Primary_Scheduler bodycontroller Sched_Server_Canvas 473 263 
ME_Scheduler Me_Primary_Scheduler enginemanagement Sched_Server_Canvas 292 263 
ME_Scheduler Me_Primary_Scheduler canbus Sched_Server_Canvas 97 266 
ME_Scheduling_Server Me_Server acquisition_task Sched_Server_Canvas 556 118 
ME_Scheduling_Server Me_Server failure_management_task Sched_Server_Canvas 461 15 
ME_Scheduling_Server Me_Server setpoint_task Sched_Server_Canvas 261 22 
ME_Scheduling_Server Me_Server control_task Sched_Server_Canvas 361 118 
ME_Scheduling_Server Me_Server acquisition_message_task Sched_Server_Canvas 145 105 
ME_Scheduling_Server Me_Server diagnosis_message_task Sched_Server_Canvas 2 20 
ME_Operation Me_Simple_Operation acquisition Operation_Canvas 200 210 
ME_Operation Me_Simple_Operation interpretation Operation_Canvas 40 210 
ME_Operation Me_Simple_Operation send_receive_interpretation Operation_Canvas 520 125 
ME_Operation Me_Simple_Operation diagnosis Operation_Canvas 360 125 
ME_Operation Me_Simple_Operation send_receive_diagnosis Operation_Canvas 200 125 
ME_Operation Me_Simple_Operation limp_home Operation_Canvas 40 125 
ME_Operation Me_Simple_Operation setpoint Operation_Canvas 520 40 
ME_Operation Me_Simple_Operation application_condition Operation_Canvas 360 40 
ME_Operation Me_Simple_Operation basic_function Operation_Canvas 200 40 
ME_Operation Me_Simple_Operation controller Operation_Canvas 40 40 
ME_Transaction Me_Regular_Transaction failuremanagement Transaction_Canvas 200 40 
ME_Transaction Me_Regular_Transaction control Transaction_Canvas 40 40 
ME_Link Me_External_Link failure_event,failuremanagement failuremanagement 85 55 
ME_Link Me_Internal_Link diagnosis_out,failuremanagement failuremanagement 465 55 
ME_Link Me_Internal_Link limp_in,failuremanagement failuremanagement 845 55 
ME_Link Me_Internal_Link limp_out,failuremanagement failuremanagement 1225 55 
ME_Link Me_External_Link control_event,control control 85 55 
ME_Link Me_Internal_Link input_acquisition_out,control control 465 55 
ME_Link Me_Internal_Link interpretation_in,control control 845 55 
ME_Link Me_Internal_Link interpretation_out,control control 1225 55 
ME_Link Me_Internal_Link setpoint_in,control control 1605 55 
ME_Link Me_Internal_Link setpoint_out,control control 1985 55 
ME_Link Me_Internal_Link application_out,control control 2365 55 
ME_Link Me_Internal_Link basic_out,control control 2745 55 
ME_Link Me_Internal_Link controller_out,control control 3125 55 
ME_Event_Handler Me_Simple_Event_Handler 1,failuremanagement failuremanagement 230 40 
ME_Event_Handler Me_Simple_Event_Handler 2,failuremanagement failuremanagement 610 40 
ME_Event_Handler Me_Simple_Event_Handler 3,failuremanagement failuremanagement 990 40 
ME_Event_Handler Me_Simple_Event_Handler 1,control control 230 40 
ME_Event_Handler Me_Simple_Event_Handler 2,control control 610 40 
ME_Event_Handler Me_Simple_Event_Handler 3,control control 990 40 
ME_Event_Handler Me_Simple_Event_Handler 4,control control 1370 40 
ME_Event_Handler Me_Simple_Event_Handler 5,control control 1750 40 
ME_Event_Handler Me_Simple_Event_Handler 6,control control 2130 40 
ME_Event_Handler Me_Simple_Event_Handler 7,control control 2510 40 
ME_Event_Handler Me_Simple_Event_Handler 8,control control 2890 40 
