 
ME_Processing_Resource Me_Regular_Processor cpu1 Proc_Res_Canvas 313 104 
ME_Scheduler Me_Primary_Scheduler cpu1_scheduler Proc_Res_Canvas 40 40 
ME_Scheduler Me_Primary_Scheduler cpu1_scheduler Sched_Server_Canvas 189 222 
ME_Scheduling_Server Me_Server gnc_tmtc_process_gnc_th_sched_server Sched_Server_Canvas 297 63 
ME_Scheduling_Server Me_Server gnc_tmtc_process_tmtc_th_sched_server Sched_Server_Canvas 40 40 
ME_Operation Me_Enclosing_Operation gnc_tmtc_process_gnc_th_operations Operation_Canvas 427 62 
ME_Operation Me_Simple_Operation gnc_wrapper.impl Operation_Canvas 458 162 
ME_Operation Me_Enclosing_Operation gnc_tmtc_process_tmtc_th_operations Operation_Canvas 188 56 
ME_Operation Me_Simple_Operation tmtc_wrapper.impl Operation_Canvas 109 179 
ME_Transaction Me_Regular_Transaction gnc_tmtc_process_gnc_th Transaction_Canvas 200 40 
ME_Transaction Me_Regular_Transaction gnc_tmtc_process_tmtc_th Transaction_Canvas 40 40 
ME_Link Me_External_Link gnc_tmtc_process_gnc_th_activation_event,gnc_tmtc_process_gnc_th gnc_tmtc_process_gnc_th 85 55 
ME_Link Me_Internal_Link gnc_tmtc_process_gnc_th_output_event,gnc_tmtc_process_gnc_th gnc_tmtc_process_gnc_th 465 55 
ME_Link Me_External_Link gnc_tmtc_process_tmtc_th_activation_event,gnc_tmtc_process_tmtc_th gnc_tmtc_process_tmtc_th 85 55 
ME_Link Me_Internal_Link gnc_tmtc_process_tmtc_th_output_event,gnc_tmtc_process_tmtc_th gnc_tmtc_process_tmtc_th 465 55 
ME_Event_Handler Me_Simple_Event_Handler 1,gnc_tmtc_process_gnc_th gnc_tmtc_process_gnc_th 230 40 
ME_Event_Handler Me_Simple_Event_Handler 1,gnc_tmtc_process_tmtc_th gnc_tmtc_process_tmtc_th 230 40 
