 
ME_Processing_Resource Me_Regular_Processor cpu1 Proc_Res_Canvas 116 92 
ME_Processing_Resource Me_Regular_Processor cpu2 Proc_Res_Canvas 539 106 
ME_Processing_Resource Me_Packet_Based_Network can_bus Proc_Res_Canvas 330 208 
ME_Timer Me_System_Timer cpu1 Proc_Res_Canvas 59 207 
ME_Timer Me_System_Timer cpu2 Proc_Res_Canvas 679 197 
ME_Driver Me_Packet_Driver cpu1,can_bus Proc_Res_Canvas 253 306 
ME_Driver Me_Packet_Driver cpu2,can_bus Proc_Res_Canvas 510 301 
ME_Scheduler Me_Primary_Scheduler cpu1_sched Proc_Res_Canvas 49 4 
ME_Scheduler Me_Primary_Scheduler cpu2_sched Proc_Res_Canvas 587 0 
ME_Scheduler Me_Primary_Scheduler can_scheduler Proc_Res_Canvas 331 111 
ME_Scheduler Me_Primary_Scheduler cpu1_sched Sched_Server_Canvas 206 95 
ME_Scheduler Me_Primary_Scheduler cpu2_sched Sched_Server_Canvas 378 95 
ME_Scheduler Me_Primary_Scheduler can_scheduler Sched_Server_Canvas 748 199 
ME_Scheduling_Server Me_Server read Sched_Server_Canvas 546 28 
ME_Scheduling_Server Me_Server display Sched_Server_Canvas 383 250 
ME_Scheduling_Server Me_Server check Sched_Server_Canvas 547 233 
ME_Scheduling_Server Me_Server sensor_isr Sched_Server_Canvas 24 91 
ME_Scheduling_Server Me_Server kbd_isr Sched_Server_Canvas 548 130 
ME_Scheduling_Server Me_Server read_remote Sched_Server_Canvas 40 218 
ME_Scheduling_Server Me_Server can_bus_isr Sched_Server_Canvas 26 -36 
ME_Scheduling_Server Me_Server can_isr2 Sched_Server_Canvas 385 -21 
ME_Scheduling_Server Me_Server temp_msg_stream Sched_Server_Canvas 742 77 
ME_Shared_Resource Me_Immediate_Ceiling_Resource screen Shared_Res_Canvas 53 29 
ME_Shared_Resource Me_Immediate_Ceiling_Resource measmnt_buffer Shared_Res_Canvas 273 22 
ME_Operation Me_Simple_Operation wite_avg Operation_Canvas 509 8 
ME_Operation Me_Simple_Operation write_record Operation_Canvas 516 111 
ME_Operation Me_Simple_Operation put_temp Operation_Canvas 557 259 
ME_Operation Me_Simple_Operation get_avg_temp Operation_Canvas 55 7 
ME_Operation Me_Simple_Operation get_record Operation_Canvas 31 106 
ME_Operation Me_Enclosing_Operation display Operation_Canvas 275 11 
ME_Operation Me_Enclosing_Operation read Operation_Canvas 382 211 
ME_Operation Me_Enclosing_Operation check Operation_Canvas 277 113 
ME_Operation Me_Simple_Operation sensor_isr Operation_Canvas 90 297 
ME_Operation Me_Simple_Operation kbd_isr Operation_Canvas 50 210 
ME_Operation Me_Simple_Operation read_remote Operation_Canvas 383 291 
ME_Operation Me_Simple_Operation can_send Operation_Canvas 709 11 
ME_Operation Me_Simple_Operation can_receive Operation_Canvas 718 104 
ME_Operation Me_Message_Transmission_Operation temp_msg Operation_Canvas 724 193 
ME_Transaction Me_Regular_Transaction tr_read Transaction_Canvas 15 15 
ME_Transaction Me_Regular_Transaction tr_display Transaction_Canvas 22 110 
ME_Transaction Me_Regular_Transaction tr_check Transaction_Canvas 28 209 
ME_Link Me_External_Link dis,tr_display tr_display 19 31 
ME_Link Me_Internal_Link disp_out,tr_display tr_display 351 41 
ME_Link Me_External_Link rec,tr_check tr_check 28 33 
ME_Link Me_Internal_Link rec_out,tr_check tr_check 337 41 
ME_Link Me_External_Link sensor,tr_read tr_read 3 22 
ME_Link Me_Internal_Link put,tr_read tr_read 32 230 
ME_Link Me_Internal_Link i1,tr_read tr_read 172 21 
ME_Link Me_Internal_Link i2,tr_check tr_check 169 43 
ME_Link Me_Internal_Link i1a,tr_read tr_read 344 30 
ME_Link Me_Internal_Link i1b,tr_read tr_read 466 228 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_check tr_check 252 112 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_read tr_read 228 215 
ME_Event_Handler Me_Simple_Event_Handler 2,tr_read tr_read 27 97 
ME_Event_Handler Me_Simple_Event_Handler 2,tr_check tr_check 41 120 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_display tr_display 151 23 
ME_Event_Handler Me_Simple_Event_Handler 3,tr_read tr_read 217 103 
ME_Event_Handler Me_Simple_Event_Handler 4,tr_read tr_read 425 100 
