 
ME_Processing_Resource Me_Regular_Processor cpu1 Proc_Res_Canvas 85 42 
ME_Timer Me_System_Timer cpu1 Proc_Res_Canvas 140 201 
ME_Scheduler Me_Primary_Scheduler cpu1_sched Proc_Res_Canvas 310 72 
ME_Scheduler Me_Primary_Scheduler cpu1_sched Sched_Server_Canvas 337 119 
ME_Scheduling_Server Me_Server read Sched_Server_Canvas 51 23 
ME_Scheduling_Server Me_Server display Sched_Server_Canvas 87 142 
ME_Scheduling_Server Me_Server check Sched_Server_Canvas 157 268 
ME_Scheduling_Server Me_Server sensor_isr Sched_Server_Canvas 521 34 
ME_Scheduling_Server Me_Server kbd_isr Sched_Server_Canvas 527 204 
ME_Shared_Resource Me_Immediate_Ceiling_Resource screen Shared_Res_Canvas 53 29 
ME_Shared_Resource Me_Immediate_Ceiling_Resource measmnt_buffer Shared_Res_Canvas 273 22 
ME_Operation Me_Simple_Operation wite_avg Operation_Canvas 509 8 
ME_Operation Me_Simple_Operation write_record Operation_Canvas 516 111 
ME_Operation Me_Simple_Operation put_temp Operation_Canvas 557 259 
ME_Operation Me_Simple_Operation get_avg_temp Operation_Canvas 24 6 
ME_Operation Me_Simple_Operation get_record Operation_Canvas 31 106 
ME_Operation Me_Enclosing_Operation display Operation_Canvas 275 11 
ME_Operation Me_Enclosing_Operation read Operation_Canvas 350 258 
ME_Operation Me_Enclosing_Operation check Operation_Canvas 277 113 
ME_Operation Me_Simple_Operation sensor_isr Operation_Canvas 90 297 
ME_Operation Me_Simple_Operation kbd_isr Operation_Canvas 50 210 
ME_Transaction Me_Regular_Transaction tr_read Transaction_Canvas 15 15 
ME_Transaction Me_Regular_Transaction tr_display Transaction_Canvas 22 110 
ME_Transaction Me_Regular_Transaction tr_check Transaction_Canvas 28 209 
ME_Link Me_External_Link dis,tr_display tr_display 19 31 
ME_Link Me_Internal_Link disp_out,tr_display tr_display 351 41 
ME_Link Me_External_Link rec,tr_check tr_check 28 33 
ME_Link Me_Internal_Link rec_out,tr_check tr_check 337 41 
ME_Link Me_External_Link sensor,tr_read tr_read 3 22 
ME_Link Me_Internal_Link put,tr_read tr_read 372 26 
ME_Link Me_Internal_Link i1,tr_read tr_read 191 22 
ME_Link Me_Internal_Link i2,tr_check tr_check 169 43 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_check tr_check 252 112 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_read tr_read 262 84 
ME_Event_Handler Me_Simple_Event_Handler 2,tr_read tr_read 56 89 
ME_Event_Handler Me_Simple_Event_Handler 2,tr_check tr_check 41 120 
ME_Event_Handler Me_Simple_Event_Handler 1,tr_display tr_display 151 23 
