 
ME_Processing_Resource Me_Regular_Processor cpu1 Proc_Res_Canvas 15 15 
ME_Scheduler Me_Primary_Scheduler sc_cpu1 Proc_Res_Canvas 217 29 
ME_Scheduler Me_Primary_Scheduler sc_cpu1 Sched_Server_Canvas 252 14 
ME_Scheduling_Server Me_Server ss_bursty Sched_Server_Canvas 15 15 
ME_Scheduling_Server Me_Server ss_low Sched_Server_Canvas 482 32 
ME_Scheduling_Server Me_Server high Sched_Server_Canvas 244 141 
ME_Operation Me_Simple_Operation low Operation_Canvas 15 15 
ME_Operation Me_Simple_Operation bursty Operation_Canvas 204 12 
ME_Operation Me_Simple_Operation high Operation_Canvas 375 15 
ME_Transaction Me_Regular_Transaction low Transaction_Canvas 15 15 
ME_Transaction Me_Regular_Transaction bursty Transaction_Canvas 222 14 
ME_Transaction Me_Regular_Transaction high_tr Transaction_Canvas 414 19 
ME_Link Me_External_Link e1,low low 15 15 
ME_Link Me_Internal_Link e2,low low 135 15 
ME_Link Me_External_Link e1,bursty bursty 165 15 
ME_Link Me_Internal_Link e2,bursty bursty 423 17 
ME_Link Me_External_Link e1,high_tr high_tr 15 15 
ME_Link Me_Internal_Link e2,high_tr high_tr 330 12 
ME_Event_Handler Me_Simple_Event_Handler 1,low low 129 97 
ME_Event_Handler Me_Simple_Event_Handler 1,bursty bursty 280 87 
ME_Event_Handler Me_Simple_Event_Handler 1,high_tr high_tr 141 96 
