 
ME_Processing_Resource Me_Packet_Based_Network syscom Proc_Res_Canvas 439 188 
ME_Processing_Resource Me_Regular_Processor cpu Proc_Res_Canvas 189 196 
ME_Scheduler Me_Primary_Scheduler syscom_scheduler Proc_Res_Canvas 200 40 
ME_Scheduler Me_Primary_Scheduler cpu_scheduler Proc_Res_Canvas 40 40 
ME_Scheduler Me_Primary_Scheduler syscom_scheduler Sched_Server_Canvas 584 208 
ME_Scheduler Me_Primary_Scheduler cpu_scheduler Sched_Server_Canvas 79 206 
ME_Scheduling_Server Me_Server tr0_op1_svr Sched_Server_Canvas 497 102 
ME_Scheduling_Server Me_Server tr0_op0_svr Sched_Server_Canvas -1 107 
ME_Scheduling_Server Me_Server tr0_op2_svr Sched_Server_Canvas 46 26 
ME_Scheduling_Server Me_Server tr1_op0_svr Sched_Server_Canvas 213 111 
ME_Scheduling_Server Me_Server tr1_op1_svr Sched_Server_Canvas 669 97 
ME_Scheduling_Server Me_Server tr1_op2_svr Sched_Server_Canvas 229 27 
ME_Operation Me_Message_Transmission_Operation tr0_op1 Operation_Canvas 200 125 
ME_Operation Me_Simple_Operation tr0_op0 Operation_Canvas 40 125 
ME_Operation Me_Simple_Operation tr0_op2 Operation_Canvas 520 40 
ME_Operation Me_Simple_Operation tr1_op0 Operation_Canvas 360 40 
ME_Operation Me_Message_Transmission_Operation tr1_op1 Operation_Canvas 200 40 
ME_Operation Me_Simple_Operation tr1_op2 Operation_Canvas 40 40 
ME_Transaction Me_Regular_Transaction transaction_0 Transaction_Canvas 200 40 
ME_Transaction Me_Regular_Transaction transaction_1 Transaction_Canvas 40 40 
ME_Link Me_External_Link tr0_ex_evt,transaction_0 transaction_0 85 55 
ME_Link Me_Internal_Link tr0_in_evt0,transaction_0 transaction_0 465 55 
ME_Link Me_Internal_Link tr0_in_evt1,transaction_0 transaction_0 845 55 
ME_Link Me_Internal_Link tr0_in_evt2,transaction_0 transaction_0 1225 55 
ME_Link Me_External_Link tr1_ex_evt,transaction_1 transaction_1 85 55 
ME_Link Me_Internal_Link tr1_in_evt0,transaction_1 transaction_1 465 55 
ME_Link Me_Internal_Link tr1_in_evt1,transaction_1 transaction_1 845 55 
ME_Link Me_Internal_Link tr1_in_evt2,transaction_1 transaction_1 1225 55 
ME_Event_Handler Me_Simple_Event_Handler 1,transaction_0 transaction_0 230 40 
ME_Event_Handler Me_Simple_Event_Handler 2,transaction_0 transaction_0 610 40 
ME_Event_Handler Me_Simple_Event_Handler 3,transaction_0 transaction_0 990 40 
ME_Event_Handler Me_Simple_Event_Handler 1,transaction_1 transaction_1 230 40 
ME_Event_Handler Me_Simple_Event_Handler 2,transaction_1 transaction_1 610 40 
ME_Event_Handler Me_Simple_Event_Handler 3,transaction_1 transaction_1 990 40 
