 
ME_Processing_Resource Me_Regular_Processor cpu1 Proc_Res_Canvas 205 128 
ME_Scheduler Me_Primary_Scheduler sc_cpu1 Proc_Res_Canvas 40 40 
ME_Scheduler Me_Primary_Scheduler sc_cpu1 Sched_Server_Canvas 360 40 
ME_Scheduling_Server Me_Server ss_med Sched_Server_Canvas 520 40 
ME_Scheduling_Server Me_Server ss_low Sched_Server_Canvas 200 40 
ME_Scheduling_Server Me_Server high Sched_Server_Canvas 40 40 
ME_Operation Me_Simple_Operation low Operation_Canvas 360 40 
ME_Operation Me_Simple_Operation med Operation_Canvas 200 40 
ME_Operation Me_Simple_Operation high Operation_Canvas 40 40 
ME_Transaction Me_Regular_Transaction low Transaction_Canvas 360 40 
ME_Transaction Me_Regular_Transaction med Transaction_Canvas 200 40 
ME_Transaction Me_Regular_Transaction high_tr Transaction_Canvas 40 40 
ME_Link Me_External_Link e1,low low 85 55 
ME_Link Me_Internal_Link e2,low low 465 55 
ME_Link Me_External_Link e1,med med 85 55 
ME_Link Me_Internal_Link e2,med med 1605 55 
ME_Link Me_Internal_Link e11,med med 465 55 
ME_Link Me_Internal_Link e12,med med 845 55 
ME_Link Me_Internal_Link e13,med med 1225 55 
ME_Link Me_External_Link e1,high_tr high_tr 85 55 
ME_Link Me_Internal_Link e2,high_tr high_tr 465 55 
ME_Event_Handler Me_Simple_Event_Handler 1,low low 230 40 
ME_Event_Handler Me_Simple_Event_Handler 1,med med 610 40 
ME_Event_Handler Me_Simple_Event_Handler 2,med med 230 40 
ME_Event_Handler Me_Simple_Event_Handler 3,med med 1370 40 
ME_Event_Handler Me_Simple_Event_Handler 4,med med 990 40 
ME_Event_Handler Me_Simple_Event_Handler 1,high_tr high_tr 230 40 
