 
ME_Processing_Resource Me_Regular_Processor procesador Proc_Res_Canvas 15 15 
ME_Scheduler Me_Primary_Scheduler scheduler Proc_Res_Canvas 234 14 
ME_Scheduler Me_Primary_Scheduler scheduler Sched_Server_Canvas 219 9 
ME_Scheduling_Server Me_Server t1 Sched_Server_Canvas 15 15 
ME_Scheduling_Server Me_Server t2 Sched_Server_Canvas 444 16 
ME_Scheduling_Server Me_Server t3 Sched_Server_Canvas 413 114 
ME_Scheduling_Server Me_Server ap Sched_Server_Canvas 615 15 
ME_Operation Me_Simple_Operation t1_exe Operation_Canvas 15 15 
ME_Operation Me_Simple_Operation t2_exe Operation_Canvas 186 17 
ME_Operation Me_Simple_Operation t3_exe Operation_Canvas 346 15 
ME_Operation Me_Simple_Operation t4_exe Operation_Canvas 510 21 
ME_Transaction Me_Regular_Transaction tarea1 Transaction_Canvas 15 15 
ME_Transaction Me_Regular_Transaction tarea2 Transaction_Canvas 215 17 
ME_Transaction Me_Regular_Transaction tarea3 Transaction_Canvas 407 16 
ME_Transaction Me_Regular_Transaction aperiodica Transaction_Canvas 585 15 
ME_Link Me_External_Link in1,tarea1 tarea1 9 36 
ME_Link Me_Internal_Link ex1,tarea1 tarea1 309 29 
ME_Link Me_External_Link in2,tarea2 tarea2 15 15 
ME_Link Me_Internal_Link ex2,tarea2 tarea2 318 18 
ME_Link Me_External_Link in3,tarea3 tarea3 165 15 
ME_Link Me_Internal_Link ex3,tarea3 tarea3 460 21 
ME_Link Me_External_Link in4,aperiodica aperiodica 165 15 
ME_Link Me_Internal_Link ex4,aperiodica aperiodica 285 15 
ME_Event_Handler Me_Simple_Event_Handler 1,tarea1 tarea1 147 13 
ME_Event_Handler Me_Simple_Event_Handler 1,tarea2 tarea2 135 15 
ME_Event_Handler Me_Simple_Event_Handler 1,tarea3 tarea3 298 15 
ME_Event_Handler Me_Simple_Event_Handler 1,aperiodica aperiodica 186 47 
